server:
  port:8080
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled:true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto:update
      show-sql:true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to RBI accounts related local APIs "
  contactDetails:
    name: "Shreyas V - Developer"
    email: "Shreyas@rbi.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345