server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
#    mysql db configs
#    url: jdbc:mysql://localhost:3306/accountsdb
#    username: root
#    password: root
#  sql:
#    init:
#      mode: always
    url: jdbc:h2:mem:testdb
    username: sa
    password: ''
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: "optional:configserver:http://localhost:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "RBI accounts microservice"
    version: "1.0"

#rabbitmq:
#  host: "localhost"
#  port: 5672
#  username: "guest"
#  password: "guest"