spring:
  application:
    name: "configserver"
  profiles:
#    active: native
    active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
#          search-locations: "file:///D:/Java/RBI_Configs"
        git:
          uri: "https://github.com/ShreyasAV01/RBI_Config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true


encrypt:
  key: "45D81EC1E12ERF61DF9AD8D3E5BB397F9"

server:
  port: 8071



